application: login
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /secret
  script: main.application
  login: required

- url: .*
  script: main.application

libraries:
- name: jinja2
  version: latest