application: clock
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images/

- url: /cuenta
  script: cuenta.application
  login: required

- url: /prefs
  script: prefs.application
  login: required

- url: /productos
  script: productos.application

- url: /crud(.*)
  script: crud.application

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

env_variables:
  TEXTO_DUMMY: "Lorem Ipsum"
