application: sample-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1d"

handlers:
- url: /css
  static_dir: static/css
  expiration: "6h"
- url: /img
  static_dir: static/img
- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
- name: markupsafe
  version: latest